// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package sqlc

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT 1::bigint AS result
`

func (q *Queries) HealthCheck(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, healthCheck)
	var result int64
	err := row.Scan(&result)
	return result, err
}
