// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type VoiceEnrollmentSample struct {
	ID              string    `json:"id"`
	OwnerUserID     string    `json:"owner_user_id"`
	Slot            int16     `json:"slot"`
	ProviderLabel   string    `json:"provider_label"`
	FileName        string    `json:"file_name"`
	FilePath        string    `json:"file_path"`
	MediaType       string    `json:"media_type"`
	SizeBytes       int64     `json:"size_bytes"`
	DurationSeconds float64   `json:"duration_seconds"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
