// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice_enrollment.sql

package sqlc

import (
	"context"
)

const createVoiceEnrollmentSample = `-- name: CreateVoiceEnrollmentSample :one
WITH available_slot AS (
    SELECT slot
    FROM generate_series(0, 3) AS slot
    WHERE NOT EXISTS (
        SELECT 1 FROM voice_enrollment_samples
        WHERE owner_user_id = $1 AND voice_enrollment_samples.slot = slot
    )
    ORDER BY slot
    LIMIT 1
)
INSERT INTO voice_enrollment_samples (
    owner_user_id, slot, provider_label, file_name, file_path,
    media_type, size_bytes, duration_seconds
)
SELECT $1, slot, $2, $3, $4, $5, $6, $7
FROM available_slot
ON CONFLICT (owner_user_id, slot) DO NOTHING
RETURNING id, owner_user_id, slot, provider_label, file_name, file_path,
          media_type, size_bytes, duration_seconds, created_at, updated_at
`

type CreateVoiceEnrollmentSampleParams struct {
	OwnerUserID     string  `json:"owner_user_id"`
	ProviderLabel   string  `json:"provider_label"`
	FileName        string  `json:"file_name"`
	FilePath        string  `json:"file_path"`
	MediaType       string  `json:"media_type"`
	SizeBytes       int64   `json:"size_bytes"`
	DurationSeconds float64 `json:"duration_seconds"`
}

func (q *Queries) CreateVoiceEnrollmentSample(ctx context.Context, arg CreateVoiceEnrollmentSampleParams) (VoiceEnrollmentSample, error) {
	row := q.db.QueryRowContext(ctx, createVoiceEnrollmentSample,
		arg.OwnerUserID,
		arg.ProviderLabel,
		arg.FileName,
		arg.FilePath,
		arg.MediaType,
		arg.SizeBytes,
		arg.DurationSeconds,
	)
	var i VoiceEnrollmentSample
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Slot,
		&i.ProviderLabel,
		&i.FileName,
		&i.FilePath,
		&i.MediaType,
		&i.SizeBytes,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVoiceEnrollmentSample = `-- name: DeleteVoiceEnrollmentSample :one
DELETE FROM voice_enrollment_samples
WHERE id = $1 AND owner_user_id = $2
RETURNING id, owner_user_id, slot, provider_label, file_name, file_path,
          media_type, size_bytes, duration_seconds, created_at, updated_at
`

type DeleteVoiceEnrollmentSampleParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) DeleteVoiceEnrollmentSample(ctx context.Context, arg DeleteVoiceEnrollmentSampleParams) (VoiceEnrollmentSample, error) {
	row := q.db.QueryRowContext(ctx, deleteVoiceEnrollmentSample, arg.ID, arg.OwnerUserID)
	var i VoiceEnrollmentSample
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Slot,
		&i.ProviderLabel,
		&i.FileName,
		&i.FilePath,
		&i.MediaType,
		&i.SizeBytes,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVoiceEnrollmentSample = `-- name: GetVoiceEnrollmentSample :one
SELECT id, owner_user_id, slot, provider_label, file_name, file_path,
       media_type, size_bytes, duration_seconds, created_at, updated_at
FROM voice_enrollment_samples
WHERE id = $1 AND owner_user_id = $2
`

type GetVoiceEnrollmentSampleParams struct {
	ID          string `json:"id"`
	OwnerUserID string `json:"owner_user_id"`
}

func (q *Queries) GetVoiceEnrollmentSample(ctx context.Context, arg GetVoiceEnrollmentSampleParams) (VoiceEnrollmentSample, error) {
	row := q.db.QueryRowContext(ctx, getVoiceEnrollmentSample, arg.ID, arg.OwnerUserID)
	var i VoiceEnrollmentSample
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Slot,
		&i.ProviderLabel,
		&i.FileName,
		&i.FilePath,
		&i.MediaType,
		&i.SizeBytes,
		&i.DurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVoiceEnrollmentSamples = `-- name: ListVoiceEnrollmentSamples :many
SELECT id, owner_user_id, slot, provider_label, file_name, file_path,
       media_type, size_bytes, duration_seconds, created_at, updated_at
FROM voice_enrollment_samples
WHERE owner_user_id = $1
ORDER BY slot
`

func (q *Queries) ListVoiceEnrollmentSamples(ctx context.Context, ownerUserID string) ([]VoiceEnrollmentSample, error) {
	rows, err := q.db.QueryContext(ctx, listVoiceEnrollmentSamples, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VoiceEnrollmentSample{}
	for rows.Next() {
		var i VoiceEnrollmentSample
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Slot,
			&i.ProviderLabel,
			&i.FileName,
			&i.FilePath,
			&i.MediaType,
			&i.SizeBytes,
			&i.DurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
